name: "Check Relevant Changes"
description: "Checks if changes are relevant"

outputs:
  relevant_changes:
    description: "true if changes require a build"
    value: ${{ steps.output.outputs.relevant_changes }}

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      with:
        files: |
          .github/actions/check-changes/action.yaml
          .github/actions/check-changes/download-and-configure-sealights/action.yaml
          .github/workflows/validate.yaml
          Makefile
          **/*.go
          bundle/**
          config/**
          go.mod
          go.sum
          **/testdata/**
        files_ignore: |
          **/*.md
          **/*.adoc
          .rhdh/** 

    - name: List all changed files (for troubleshooting)
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Output
      id: output
      shell: bash
      run: |
        echo "relevant_changes=${{ steps.changed-files.outputs.any_changed }}" >> $GITHUB_OUTPUT
