name: PR golangci-lint Config Validator

on:
  pull_request:
    paths:
      - '.golangci.yaml'
    branches:
      - main
      - rhdh-1.[0-9]+
      - 1.[0-9]+.x
      - release-1.[0-9]+

jobs:
  golangci-config-validator:
    runs-on: ubuntu-latest
    name: golangci-lint Config Validator
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'

      - name: Validate golangci-lint config
        run: make lint-config-check
