name: Nightly checks

on:
  # workflow_dispatch so that it can be triggered manually if needed
  workflow_dispatch:
  schedule:
    - cron: "34 23 * * *"

jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - main
          - release-1.7
          - release-1.6
          - release-1.5
    name: 'Nightly Tests for ${{ matrix.branch }}'
    concurrency:
      group: '${{ github.workflow }}-${{ matrix.branch }}'
      cancel-in-progress: true
    env:
      CONTAINER_TOOL: podman
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 # default branch will be checked out by default on scheduled workflows
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: 'go.mod'

      - name: Set env vars
        run: |
          branch=${{ matrix.branch }}
          distLocation="dist/rhdh/install.yaml"
          OPERATOR_MANIFEST="${{ github.workspace }}/${distLocation}"
          proto="file://"
          if [[ "${branch}" != "main" ]]; then
            version="${branch#release-}"
            major=$(echo $version | cut -d. -f1)
            minor=$(echo $version | cut -d. -f2)
            OPERATOR_MANIFEST="${{ github.workspace }}/tests/e2e/testdata/rhdh-operator-${version}.yaml"
            # TODO(rm3l): remove this once 1.6 is the minimal supported version
            if [[ $major -ge 1 && $minor -ge 6 ]]; then
              OPERATOR_MANIFEST="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${branch}/${distLocation}"
              proto=""
            fi
          fi
          echo "OPERATOR_MANIFEST=${OPERATOR_MANIFEST}" >> $GITHUB_ENV
          OPERATOR_IMAGE=$(curl -s "${proto}${OPERATOR_MANIFEST}" | yq 'select(.kind == "Deployment" and .metadata.labels.app == "rhdh-operator") | .spec.template.spec.containers[0].image')
          echo "OPERATOR_IMAGE=${OPERATOR_IMAGE}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Check if operator image exists in remote registry
        id: operator-image-existence-checker
        run: |
          echo "OPERATOR_IMAGE_EXISTS=$(skopeo inspect "docker://${{ env.OPERATOR_IMAGE }}" > /dev/null && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: Display warning if image was not found
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'false' }}
        run: |
          echo "::warning ::Operator Image ${{ env.OPERATOR_IMAGE }} not found for testing the ${{ matrix.branch }} branch. It might have expired. E2E tests will be skipped for ${{ matrix.branch }}."

      - name: Generate Kind Config
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
        run: |
          cat <<EOF > /tmp/kind-config.yaml
          apiVersion: kind.x-k8s.io/v1alpha4
          kind: Cluster
          nodes:
            - role: control-plane
              extraPortMappings:
                - containerPort: 80
                  hostPort: 80
                  protocol: TCP
                - containerPort: 443
                  hostPort: 443
                  protocol: TCP
          EOF

      - name: Create Kind cluster (E2E)
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          config: /tmp/kind-config.yaml
          ignore_failed_clean: true

      - name: Install Ingress Controller
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
        run: |
          kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s

      - name: Download and configure Sealights
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
        uses: ./.github/actions/download-and-configure-sealights
        with:
          sealights-agent-token: '${{ secrets.SEALIGHTS_AGENT_TOKEN }}'

#      - name: Run SeaLights scan for tests
#        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
#        env:
#          SEALIGHTS_TEST_STAGE: "E2E Tests"
#          SEALIGHTS_LAB_ID: "rhdh-${{ github.ref_name }}-labid"
#        run: |
#          echo "[SeaLights] Running the SeaLights scan"
#          ./slcli scan \
#            --bsid buildSessionId.txt \
#            --path-to-scanner ./slgoagent \
#            --workspacepath "./" \
#            --scm git \
#            --scmBaseUrl https://github.com/redhat-developer/rhdh-operator \
#            --scmProvider github
      - name: Start Sealights test session
        if: vars.SEALIGHTS_DISABLE != 'true' && steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true'
        env:
          SEALIGHTS_TEST_STAGE: "E2E Tests"
        run: |
          ./slcli test start-stage --bsid=buildSessionId.txt --testStage "${SEALIGHTS_TEST_STAGE}"

      - name: Run E2E tests
        if: ${{ steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' }}
        env:
          BACKSTAGE_OPERATOR_TESTS_PLATFORM: kind
          BACKSTAGE_OPERATOR_TESTS_K8S_CREATE_INGRESS: 'true'
          BACKSTAGE_OPERATOR_TESTS_K8S_INGRESS_DOMAIN: '127.0.0.1.sslip.io'
          BACKSTAGE_OPERATOR_TESTS_APP_REACHABILITY_TIMEOUT: ${{ vars.BACKSTAGE_OPERATOR_TESTS_APP_REACHABILITY_TIMEOUT }}
          OPERATOR_MANIFEST: ${{ env.OPERATOR_MANIFEST }}
          IMG: ${{ env.OPERATOR_IMAGE }}
          BRANCH: ${{ matrix.branch }}
          SEALIGHTS_TEST_STAGE: "E2E Tests"
        run: make test-e2e

      - name: Upload test results to Sealights
        if: vars.SEALIGHTS_DISABLE != 'true' && steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' && always()
        env:
          SEALIGHTS_TEST_STAGE: "E2E Tests"
        run: |
          ls -lhrta
          ./slcli test upload-reports --bsid=buildSessionId.txt

      - name: End Sealights test session
        if: vars.SEALIGHTS_DISABLE != 'true' && steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' && always()
        env:
          SEALIGHTS_TEST_STAGE: "E2E Tests"
        run: |
          ./slcli test end-stage --bsid=buildSessionId.txt --executionId "${SEALIGHTS_TEST_STAGE}"

      - name: Clean all SeaLights secret stuff
        if: vars.SEALIGHTS_DISABLE != 'true' && steps.operator-image-existence-checker.outputs.OPERATOR_IMAGE_EXISTS == 'true' && always()
        run: |
          echo "[SeaLights] Cleaning up after SeaLights run"
          rm -f sltoken.txt || true
